DROP TABLE XCONSTRAINTS_REFERENCIALS;
DROP TABLE XDDL_TABLE;
DROP TABLE XDML_ALL;
DROP TABLE XTABLE_DATATYPES_CATALOGUE;
DROP TABLE XTABLE_SCRIPTS;
DROP TABLE XVIEW_SCRIPTS;


SELECT * FROM XDML_ALL;
SELECT * FROM XDDL_TABLE;
SELECT * FROM XVIEW_SCRIPTS;
SELECT * FROM XCONSTRAINTS_REFERENCIALS;
SELECT * FROM XTABLE_SCRIPTS;
SELECT * FROM XTABLE_DATATYPES_CATALOGUE;

SELECT TEXT FROM ALL_SOURCE WHERE OWNER  = 'SYS' AND NAME = 'DBMS_TYPES' AND TYPE = 'PACKAGE';
